# Generated by Django 5.0.1 on 2024-10-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(db_column='ID_repartidor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='ID_pedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado_pedido', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=10, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='ID_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(db_column='ID_envio', primary_key=True, serialize=False)),
                ('numero_seguimiento', models.IntegerField(blank=True, null=True)),
                ('direccion_origen', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado_envio', models.CharField(blank=True, choices=[('no_enviado', 'No enviado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('devuelto', 'Devuelto')], max_length=12, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='ID_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pedido')),
                ('id_repartidor', models.ForeignKey(blank=True, db_column='ID_repartidor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.repartidor')),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.AddField(
            model_name='repartidor',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(db_column='ID_notificacion', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado_envio', models.CharField(blank=True, choices=[('no_enviado', 'No enviado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('devuelto', 'Devuelto')], max_length=12, null=True)),
                ('id_envio', models.ForeignKey(blank=True, db_column='ID_envio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.envio')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.AutoField(db_column='ID_gerente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='ID_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'gerente',
            },
        ),
    ]
